name: sigame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  html: ^0.15.5
  http: ^1.3.0
  beautiful_soup_dart: ^0.3.0
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
